系统设计入门 第一部分 初稿完成
xitu/system-design-primer pull request #1
Opened 2017-03-30 00:51 UTC by XatMassacrE

issue [#1430](https://github.com/xitu/gold-miner/issues/1430)

2017-03-30 02:14 UTC, sqrthree commented
Good job.

2017-04-07 05:29 UTC, L9m commented on README-zh-Hant.md
> +> 学习如何设计大型系统
英文有句号还是要添加一下句号

2017-04-07 05:37 UTC, L9m commented on README-zh-Hant.md
> +这个仓库就是这些资源的**有组织的集合**，它可以帮助你学习如果基于不同尺度构建系统。
它可以帮助你学习如果基于不同尺度构建系统。
-> 它可以帮助你学习如何构建可扩展的系统。

2017-04-07 05:43 UTC, L9m commented on README-zh-Hant.md
> +**练习普通的系统设计面试题**并且把你的结果和**例子的解答**进行**比较**：讨论，代码和图表。
比较 -> 对照

2017-04-07 05:50 UTC, L9m commented on README-zh-Hant.md
> +自由提交 PR 来帮助：
“自由提交 PR 来帮助：” 改成 “欢迎提交 PR 来提供帮助：”更好理解一些

2017-04-07 06:04 UTC, L9m commented on README-zh-Hant.md
> +> 各种系统设计主题的摘要，包括优点和缺点。**每一个主题都对应一个职业**。
每一个主题都对应一个职业 翻译成 每一个主题都面临着取舍和权衡。

2017-04-07 06:05 UTC, L9m commented on README-zh-Hant.md
> +    * [4 层负载均衡](#layer-4-load-balancing)
这里我都改成汉字了  = =

2017-04-07 06:11 UTC, L9m commented on README-zh-Hant.md
>  ### Step 4: Scale the design
多余的英文

2017-04-07 06:39 UTC, L9m commented on README-zh-Hant.md
> +    * [第一步：查阅拓展性的视频讲座](#step-1-review-the-scalability-video-lecture)
查阅拓展性的视频讲座 我的翻译是：回顾可扩展性（scalability）的视频讲座，scalability 应该统一一下

2017-04-07 06:46 UTC, L9m commented on README-zh-Hant.md
> +* [性能 vs 拓展性](#performance-vs-scalability)
vs 这里的意思应该是 与，表示两者的权衡
性能与拓展性
延迟与吞吐量
可用性与一致性

2017-04-07 06:48 UTC, L9m commented on README-zh-Hant.md
> +    * [强一致](#strong-consistency)
强一致 -> 强一致性

2017-04-07 06:48 UTC, L9m commented on README-zh-Hant.md
> +    * [容灾](#fail-over)
fail-over 我这里翻译的是 故障转移

2017-04-07 06:52 UTC, L9m commented on README-zh-Hant.md
> +    * [复制集](#replication)
replication 翻译的是 复制

2017-04-07 06:52 UTC, L9m commented on README-zh-Hant.md
> +    * [推送 CDNs](#push-cdns)
推送 CDNs 翻译得是 CDN 推送

2017-04-07 06:53 UTC, L9m commented on README-zh-Hant.md
> +* [负载均衡](#load-balancer)
load-balancer 是负载均衡器

2017-04-07 06:58 UTC, L9m commented on README-zh-Hant.md
> +    * [主动-被动](#active-passive)
active-passive 翻译的是 工作到备用切换(active-passive)
active-active 翻译的是 双工作切换(active-active)

2017-04-07 07:19 UTC, L9m commented on README-zh-Hant.md
>  ### Design a system that scales to millions of users on AWS
要删除一些英文的残余

2017-04-08 04:04 UTC, XatMassacrE commented
@L9m 感谢校对，目录部分全部按照你提供的译法做了修改。

2017-04-08 04:59 UTC, xiaoyusilen reviewed
校对完毕~

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +* 改善章节
> 改善章节

改成 「完善章节」 会不会好一点？

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +还需要打磨的一些内容放在了 [开发中](#under-development)。
> 还需要打磨的一些内容放在了 [开发中](#under-development)。

一些还需要完善的内容被放在了[开发中](#under-development)。
中文之间不需要加空格~

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +对**翻译**感兴趣？请查看这个 [门票](https://github.com/donnemartin/system-design-primer/issues/28)。
「门票」有点奇怪，改成「链接」或者「邀请」？

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +        * [图表数据库](#graph-database)
> [图表数据库](#graph-database)

[图数据库](#graph-database)

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +    * [Web 服务缓存](#web-server-caching)
> [Web 服务缓存](#web-server-caching)

[Web 服务器缓存](#web-server-caching)

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +    * [在数据库查询层缓存](#caching-at-the-database-query-level)
> 数据库查询层缓存

数据库查询级别的缓存，我是这么翻译的。

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +    * [对象缓存](#caching-at-the-object-level)
> 对象缓存

对象级别的缓存，我是这么翻译的。

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +        * [隐式缓存](#cache-aside)
> 隐式缓存

这个就是缓存模式吧？

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +        * [直接写入](#write-through)
我翻译的是 「直写模式」

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +        * [回调写入](#write-behind-write-back)
我翻译的是「回写模式」

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +        * [自动更新](#refresh-ahead)
刷新？

2017-04-08 04:59 UTC, xiaoyusilen commented on README-zh-Hant.md
> +对每一个核心组件进行详细深入的分析。举例来说，如果你背问到 [设计一个 url 缩写服务](solutions/system_design/pastebin/README.md)，开始讨论：
被问到，打错字了~

2017-04-08 05:05 UTC, xiaoyusilen requested changes

2017-04-08 05:05 UTC, xiaoyusilen commented on README-zh-Hant.md
> +### 源码以及查看更多
我翻译的是：相关资源和延伸阅读

2017-04-08 08:44 UTC, XatMassacrE commented on README-zh-Hant.md
> +        * [自动更新](#refresh-ahead)
是把 自动更新 改为 刷新模式 ？

2017-04-08 08:55 UTC, XatMassacrE commented on README-zh-Hant.md
> +        * [自动更新](#refresh-ahead)
我看你翻译的 刷新，那就先 刷新 吧。

2017-04-08 08:57 UTC, XatMassacrE commented
@xiaoyusilen 感谢校对，目录部分全部按照你提供的译法做了修改。

2017-04-08 08:58 UTC, XatMassacrE commented
@sqrthree 校对修改完毕。

2017-04-10 07:38 UTC, merged