第五部分翻译完成
xitu/system-design-primer pull request #2
Opened 2017-03-31 09:45 UTC by jifaxu

求校对

2017-04-08 16:11 UTC, xiaoyusilen requested changes

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> +UDP 可靠性更低但适合用在网络电话、视频聊天，流（这个不知具体指啥）和实时多人游戏上。
> streaming

这儿应该是指流媒体吧。

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> +* 你需要更快的相应速度
> 你需要更快的相应速度

你需要低延迟

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> +* REST 一般依赖几个 verbs（GET, POST, PUT, DELETE 和 PATCH），但有时候仅仅这些没法满足你的需要。举个例子，将过期的文档移动到归档文件夹里去，这样的操作可能没法简单的用上面这几个 verbs 表达。
verbs是不是需要翻译出来？

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> +### PRC 与 REST 比较
RPC

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> +| Delete an item                  | **POST** /removeItem<br/>{<br/>"itemid": "456"<br/>} | **DELETE** /items/456                    |
表格里的内容是不是也应该翻译一下？

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> +** 不要专注于一下文章的细节，专注于以下方面：**
以下

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> +有兴趣加入添加一些部分或者帮助完善某些部分吗？[加入进来吧](#contributing)！
> 有兴趣加入添加一些部分或者帮助完善某些部分吗？[加入进来吧](#contributing)！

有兴趣添加一部分或者帮助完善某些部分吗？[加入进来吧](#contributing)！

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
>  * [Contribute](#contributing)
少了一句英文翻译

2017-04-08 16:11 UTC, xiaoyusilen commented on README-zh-Hant.md
> -Credits and sources are provided throughout this repo.
这句没做翻译。

2017-04-10 15:13 UTC, L9m commented on README-zh-Hant.md
> +UDP 可靠性更低但适合用在网络电话、视频聊天，流（这个不知具体指啥）和实时多人游戏上。
streaming 这里指代的是 直播

2017-04-10 16:43 UTC, Airmacho commented on README-zh-Hant.md
> +UDP 可以通过广播将数组报发送至子网内的所有设备。这对 [DHCP](https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol) 很有用，因为子网内的设备还没有分配 IP 地址，而 IP 对于 TCP 是必须的。
数组报 -> 数据报

2017-04-10 16:46 UTC, Airmacho commented on README-zh-Hant.md
> +UDP 可靠性更低但适合用在网络电话、视频聊天，流（这个不知具体指啥）和实时多人游戏上。
IMHO 同意流媒体，就是指youtube，periscope这类

2017-04-10 16:48 UTC, Airmacho commented on README-zh-Hant.md
> +* [Facebook 对内存缓存的扩展](http://www.cs.bu.edu/~jappavoo/jappavoo.github.com/451/papers/memcache-fb.pdf)
Facebook 对内存缓存的扩展 -> Memcache 在 Facebook 的扩展

2017-04-10 16:50 UTC, Airmacho commented on README-zh-Hant.md
> +在一个 RPC 里，客户端会去调用另一个地址空间（通常是一个远程服务器）里的方法。调用代码看起来就像是调用的是一个本地方法，客户端和服务器交互的具体过程被抽象。远程调用相对于本地调用一般较慢而且可靠性更差，因此区分两者是有帮助的。热门的 RPC 框架包括 [Protobuf](https://developers.google.com/protocol-buffers/), [Thrift](h
在一个 RPC 里 -> 在 RPC 中

2017-04-10 16:53 UTC, Airmacho commented on README-zh-Hant.md
> +* **客户端程序** ── 调用客户端存根程序。就像调用本地方法一样，参数会被压入栈中。
建议不翻译 stub

2017-04-11 03:52 UTC, Airmacho commented on README-zh-Hant.md
> +当以下情况时选择本地库或者 SDK：
aka不是或者的意思。。。as known as

2017-04-11 03:57 UTC, Airmacho commented on README-zh-Hant.md
> +### 具象状态传输（REST）
REST的中文很明确，表现层状态转换

2017-04-11 04:00 UTC, Airmacho commented on README-zh-Hant.md
> +* REST 一般依赖几个 verbs（GET, POST, PUT, DELETE 和 PATCH），但有时候仅仅这些没法满足你的需要。举个例子，将过期的文档移动到归档文件夹里去，这样的操作可能没法简单的用上面这几个 verbs 表达。
verbs 这里是指 http 的动词，比如 GET, POST, PATCH/PUT 等

2017-04-11 04:05 UTC, Airmacho commented on README-zh-Hant.md
> +* **可自我描述的错误信息（HTTP 中的 状态相应）** ── 使用状态码，不要重新造轮子。
HTTP 中的 状态相应 -> HTTP 请求响应中的 status code

2017-04-11 04:13 UTC, Airmacho commented on README-zh-Hant.md
> +REST 关注于暴露数据。它最小化了客户端与服务端的联系并经常被用户公共 HTTP API。REST 使用更通常与规范化的方法来通过 URI 暴露资源，[通过 header 来表述](https://github.com/for-GET/know-your-http-well/blob/master/headers.md)并通过 GET, POST, PUT, DELETE 和 PATCH 这些
它最小化了客户端与服务端的联系并经常被用户公共 HTTP API。-> 它减少了客户端／服务端的耦合程度，经常用于公共 HTTP API 接口设计。

2017-04-11 06:14 UTC, Airmacho commented on README-zh-Hant.md
> +* 使用嵌套层次结构来获取复杂资源需要客户端和服务端多次交互来渲染单个视图。比如，获取博客的内容和其下的评论。对于在可变网络环境下的移动应用，是不希望看到这种多次请求。
为了渲染单个页面，获取被嵌套在层级结构中的复杂资源需要客户端，服务器之间多次往返通信。例如，获取博客内容及其关联评论。对于使用不确定网络环境的移动应用来说，这些多次往返通信是非常麻烦的。

2017-04-11 06:16 UTC, Airmacho commented on README-zh-Hant.md
> +| Delete an item                  | **POST** /removeItem<br/>{<br/>"itemid": "456"<br/>} | **DELETE** /items/456                    |
operation这一列可以翻译一下

2017-04-11 06:17 UTC, Airmacho commented on README-zh-Hant.md
> +* [节约](https://code.facebook.com/posts/1468950976659943/)
😂 Thrift 是一种 RPC 框架，如果译者实在没有背景知识，至少可以点进链接里了解下。

2017-04-11 06:23 UTC, Airmacho commented on README-zh-Hant.md
> +安全是一个宽泛的话题。下面这些知识对你应该足够了除非你有很多的经验、安全背景或者你正在申请一个需要安全知识的职位。
下面这些知识对你应该足够了除非你有很多的经验、安全背景或者你正在申请一个需要安全知识的职位。 -> 
除非你有相当的经验、安全方面背景或者正在申请的职位要求安全知识，你不需要了解安全基础知识以外的内容：

2017-04-11 14:50 UTC, merged