translate:初稿
xitu/system-design-primer pull request #31
Opened 2017-05-26 06:19 UTC by AceLeeWinnie

2017-06-06 08:05 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +# 在 AWS 上设计支持百万级到千万级用户的系统
在AWS上设计可扩展到百万级用户的系统

这个是标题是之前已经定好了吗???

2017-06-06 08:06 UTC, AceLeeWinnie commented on solutions/system_design/scaling_aws/README.md
> +# 在 AWS 上设计支持百万级到千万级用户的系统
不是，有更好的也可以改

2017-06-06 08:08 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +> 收集需求和问题域。
scope应该作动词讲, 调查/审视

2017-06-06 08:09 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
>  Without an interviewer to address clarifying questions, we'll define some use cases and constraints.
全文的interviewer应该指的是: 面试官

2017-06-06 08:13 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +解决这个问题是一个循序渐进的过程：1) **基准/负载 测试**， 2) 瓶颈 **概述**， 3) 当评估可选和折中方案时定位瓶颈，4) 重复，这是向可扩展的设计发展基础设计的好模式。
建议: 4) repeat, which is good pattern for evolving basic designs to scalable designs.
重复是从基础设计到可扩展设计的好模式

2017-06-06 08:17 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +**如果你应该做一个粗略的使用计算，需要和你的访谈人员明确这一点**
建议: 向你的面试官厘清你是否应该做粗略的使用计算

2017-06-06 08:18 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 400 请求 / 秒 = 10 亿请求 / 月
400 次请求 / 秒 = 10 亿次请求 / 月.
保持一致

2017-06-06 08:23 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +添加 **DNS** 服务，比如 53 号路由，将域映射到实例的公共 IP 中。
Route 53: https://aws.amazon.com/cn/route53/

2017-06-06 08:27 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * 在 **对象存储中** 单独存储静态内容
在 **对象存储** 中单独存储静态内容

2017-06-06 08:33 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 考虑使用托管像 S3 的 **对象存储** 来存储静态内容
考虑使用像 S3 这样可管理的 **对象存储** 服务来存储静态内容

2017-06-06 08:34 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 考虑使用类似 RDS 的服务来管理 **MySQL 数据库**
上一段落翻译为 像

2017-06-06 08:35 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * 多可用空间
建议: 多个可用区域

2017-06-06 08:37 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 这些相同的模式在剩下的练习中应该同样为新组件实现
建议: 这些相同的模式应当在新的组件的实现中实践.

2017-06-06 08:38 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 下面的目标试图用 **Web服务器** 解决伸缩性问题
scaling 在之前语段译作 扩展

2017-06-06 08:55 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +        * 如果你正在配置自己的 **负载均衡器**, 在多个可用性区域中设置多台服务器用于 [双活](https://github.com/donnemartin/system-design-primer#active-active) 或 [主被动活动](https://github.com/donnemartin/system-design-primer#active-passive
active-passive 主被???

2017-06-06 08:56 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +        * 如果你正在配置自己的 **负载均衡器**, 在多个可用性区域中设置多台服务器用于 [双活](https://github.com/donnemartin/system-design-primer#active-active) 或 [主被动活动](https://github.com/donnemartin/system-design-primer#active-passive
[主被动活动] > [主被]

2017-06-06 08:58 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * 在多个可用性区域的 [**主-从 故障转移**](https://github.com/donnemartin/system-design-primer#master-slave-replication) 模式中使用多个 **MySQL** 实例来改进冗余
可用性区域 > 可用区域

2017-06-06 09:01 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +我们的 **性能/负载测试** 和 **性能测试** 显示我们读操作频繁（100:1 的读写比率），并且数据库在高读请求时表现很糟糕。
**Profiling** 与之前翻译段落不一致

2017-06-06 09:08 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 额外添加和扩展 **内存缓存**，**MySQL 读取副本**也能够帮助释放在 **MySQL 写线程** 的负载。
建议: 
除了添加和扩展 **内存缓存**，**MySQL 读副本服务器**也能够帮助缓解在 **MySQL 写主服务器** 的负载。

2017-06-06 09:08 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 添加逻辑到 **网络服务器** 来区分读和写操作
**Web Server** 前后翻译不一致

2017-06-06 09:10 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 在 **MySQL 读取副本** 之前添加 **负载均衡** （不是为了减少混乱）
建议: 在**MySQL 读副本服务器** 之上添加 **负载均衡器**

2017-06-06 09:13 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 大多数服务都是读取负载大于写入负载
-heavy, -intense

2017-06-06 09:18 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * **处理消息事件** - PagerDuty
处理通知和时间

2017-06-06 09:20 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 考虑一个托管服务，比如AWS **自动扩展**
考虑使用一个托管服务，比如AWS **自动扩展**

2017-06-06 09:21 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * 设置一个最小值和最大数目的实例
设置最小和最大实例数

2017-06-06 09:24 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +        * 指标超过一段时间：
时间段内的指标???

2017-06-06 09:25 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +**注释：** **自动伸缩** 组不需要显示以减少混乱
**注释：** **自动伸缩** 组不显示以减少混乱

2017-06-06 09:30 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* 平均每秒 40,0000 次的读取请求, 可以通过扩展 **内存缓存** 来处理流行内容的读取流量，这对于处理不均匀分布的流量和流量峰值也很有用
平均每秒 40,000 次的读取请求
流行内容 > 热点内容

2017-06-06 09:31 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * **SQL读取副本** 可能会遇到处理缓存泄露的问题, 我们可能需要使用额外的SQL扩展模式
cache misses > 缓存未命中

2017-06-06 09:36 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* [反规范化](https://github.com/donnemartin/system-design-primer#denormalization)
反范式

2017-06-06 09:42 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +我们可以进一步分离我们的 [**应用服务器**](https://github.com/donnemartin/system-design-primer#application-layer) 允许独立扩展。不需要实时完成的批处理或计算可以通过队列和人员异步完成：
以允许独立扩展. 不需要实时完成的批处理任务和计算可以通过 **Queues**和**Workers**异步完成

queues, workers 可不翻译

2017-06-06 09:45 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +* [健值存储](https://github.com/donnemartin/system-design-primer#key-value-store)
键值

2017-06-06 09:46 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * [网络服务缓存](https://github.com/donnemartin/system-design-primer#web-server-caching)
前后翻译不一致

2017-06-06 09:49 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +    * 客户端的外部通讯 - [HTTP APIs 后的空闲](https://github.com/donnemartin/system-design-primer#representational-state-transfer-rest)
遵循REST的HTTP APIs

2017-06-06 09:50 UTC, 0x4ec7 commented on solutions/system_design/scaling_aws/README.md
> +### 延迟数字
延迟数字指标

2017-06-06 09:52 UTC, 0x4ec7 commented
校对完毕

2017-06-07 14:14 UTC, AceLeeWinnie reviewed
辛苦 @0x4ec7 校对啦，有些问题需要再对一下。另外不知道标题有没有更好的选择，现在看着就无聊😝。最后以后有校对建议能不能麻烦给个完整版，一个字的建议不造咋整呐。最后的最后，再次谢谢大佬！

2017-06-07 14:14 UTC, AceLeeWinnie commented on solutions/system_design/scaling_aws/README.md
> +解决这个问题是一个循序渐进的过程：1) **基准/负载 测试**， 2) 瓶颈 **概述**， 3) 当评估可选和折中方案时定位瓶颈，4) 重复，这是向可扩展的设计发展基础设计的好模式。
个人觉得后面的 which 从句修饰的是 an iterative approach 即这四个步骤组成的一系列过程。

2017-06-07 14:14 UTC, AceLeeWinnie commented on solutions/system_design/scaling_aws/README.md
> +* 大多数服务都是读取负载大于写入负载
这里没看懂...

2017-06-07 14:14 UTC, AceLeeWinnie commented on solutions/system_design/scaling_aws/README.md
> +    * 客户端的外部通讯 - [HTTP APIs 后的空闲](https://github.com/donnemartin/system-design-primer#representational-state-transfer-rest)
竟然没看出来... 我一定是做梦在翻译得...

2017-06-07 14:15 UTC, AceLeeWinnie commented
@sqrthree 这个校对是一个还是俩呢

2017-06-07 14:19 UTC, sqrthree commented
@AceLeeWinnie 一个就可以了，如果有争议的地方可以在群里讨论下。

2017-06-08 04:24 UTC, AceLeeWinnie commented
@sqrthree 经过群里各位大佬指点，决定维持原翻译，可以合啦

2017-06-08 04:32 UTC, 0x4ec7 commented
@AceLeeWinnie @sqrthree 👍

2017-06-08 06:28 UTC, linhe0x0 requested changes
英文原文要删除

2017-06-09 04:51 UTC, AceLeeWinnie commented
@sqrthree 忘了... 已删

2017-06-09 07:08 UTC, sqrthree commented on solutions/system_design/scaling_aws/README.md
> +*** 注释：为了避免重复，这篇文章的链接直接关联到 [系统设计主题](https://github.com/donnemartin/system-design-primer#index-of-system-design-topics) 的相关章节。为一讨论要点、折中方案和可选方案做参考。***
![image](https://user-images.githubusercontent.com/8622362/26964711-6aaa9216-4d25-11e7-8651-1fe3828a5273.png)

2017-06-09 07:09 UTC, linhe0x0 requested changes
文中还有一些用了斜体，麻烦也调整为粗体吧。

2017-06-09 07:09 UTC, sqrthree commented on solutions/system_design/scaling_aws/README.md
> +*** 注释：为了避免重复，这篇文章的链接直接关联到 [系统设计主题](https://github.com/donnemartin/system-design-primer#index-of-system-design-topics) 的相关章节。为一讨论要点、折中方案和可选方案做参考。***
![image](https://user-images.githubusercontent.com/8622362/26964711-6aaa9216-4d25-11e7-8651-1fe3828a5273.png)

2017-06-09 07:13 UTC, AceLeeWinnie commented
@sqrthree 现在呢

2017-06-09 07:15 UTC, sqrthree commented
@AceLeeWinnie `** `那个还不行，有 view 视图你可以看下，另外斜体好像还没改完。

2017-06-09 07:27 UTC, AceLeeWinnie commented
@sqrthree 改完了Ｏ(≧口≦)Ｏ，你看下

2017-06-09 07:46 UTC, linhe0x0 approved these changes

2017-06-09 07:47 UTC, merged